# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_member_list', models.TextField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pickup_App.User_Detail')),
            ],
            options={
                'verbose_name_plural': 'Group_Detail',
                'verbose_name': 'Group_Detail',
            },
        ),
    ]
