# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0002_group_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_detail',
            name='created_group_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
