# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0003_group_detail_created_group_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
