# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0004_user_detail_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup_Schedule_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, max_length=100, null=True)),
                ('schedule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pickup_App.User_Detail')),
            ],
            options={
                'verbose_name_plural': 'Pickup_Schedule_Detail',
                'verbose_name': 'Pickup_Schedule_Detail',
            },
        ),
    ]
