# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-25 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0005_pickup_schedule_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup_schedule_detail',
            name='fk_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pickup_App.Child_Detail'),
        ),
    ]
