# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0006_pickup_schedule_detail_fk_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup_schedule_detail',
            name='flag_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
