# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0008_accept_pickup_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_pickup_detail',
            name='fk_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pickup_App.Child_Detail'),
        ),
        migrations.AddField(
            model_name='accept_pickup_detail',
            name='request',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
