# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup_App', '0010_user_detail_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_detail',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
    ]
